name: Build Next Pipeline

on:
  pull_request:
    branches: [master, develop]

jobs:
  build_next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install dependecies
        run: npm install --no-audit --no-fund --no-optional --omit=optional
      - name: Run build
        run: pnpm build
